### ISSUE TITLE
Adptação da pipeline de predição do Portal TNO ao Slurm

### ISSUE THREAD

**Issue by rcboufleur** [linea-it/tno_pipelines_old#13]
```[tasklist]
### Tasks
- [x] Adaptação da submissão do pipeline para padrão Slurm (+Parsl)
- [x] Adaptação do sistema de monitoramento p/ Parsl
- [x] Adaptação da função abort task
- [x] Implementar a comunicação entre o container na servnode04 e a máquina loginapl
- [x] Conectar com usuário deploy da aplicação ao invés de usar usuário pessoal singulani
- [x] Fazer o deploy da aplicação (container na mesma rede da servnode04) e testar o funcionamento - updade do ambiente dev para incorporar a solução
- [x] Predict Occultation Job Progress (Pipeline) #661
```

**Comment by glaubervila** [comment]
A tarefa de monitoração finalizou essa issue  Predict Occultation Job Progress (Pipeline) #661

**Comment by gschwend** [comment]
@crisingulani posso considerar esse como Done?

**Comment by crisingulani** [comment]
@gschwend sim
